/* Generated by Yosys 0.10+16 (git sha1 d8f6d7b18, x86_64-apple-darwin20.2-clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "fibonacci.sv:10.1-48.10" *)
module fibonacci(clk, rst, done, result);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  (* src = "fibonacci.sv:16.17-16.20" *)
  input clk;
  (* src = "fibonacci.sv:23.15-23.28" *)
  wire [31:0] current_value;
  (* src = "fibonacci.sv:18.18-18.22" *)
  output done;
  (* src = "fibonacci.sv:23.30-23.40" *)
  wire [31:0] prev_value;
  (* src = "fibonacci.sv:19.23-19.29" *)
  output [31:0] result;
  (* src = "fibonacci.sv:17.17-17.20" *)
  input rst;
  sky130_fd_sc_hd__clkinv_1 _280_ (
    .A(rst),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor4_1 _281_ (
    .A(current_value[11]),
    .B(current_value[10]),
    .C(current_value[9]),
    .D(current_value[8]),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor4_1 _282_ (
    .A(current_value[15]),
    .B(current_value[14]),
    .C(current_value[13]),
    .D(current_value[12]),
    .Y(_097_)
  );
  sky130_fd_sc_hd__nand2_1 _283_ (
    .A(_096_),
    .B(_097_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__or4b_1 _284_ (
    .A(current_value[3]),
    .B(current_value[2]),
    .C(current_value[0]),
    .D_N(current_value[1]),
    .X(_099_)
  );
  sky130_fd_sc_hd__or4_1 _285_ (
    .A(current_value[7]),
    .B(current_value[6]),
    .C(current_value[5]),
    .D(current_value[4]),
    .X(_100_)
  );
  sky130_fd_sc_hd__nor4_1 _286_ (
    .A(current_value[27]),
    .B(current_value[26]),
    .C(current_value[25]),
    .D(current_value[24]),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nor4_1 _287_ (
    .A(current_value[31]),
    .B(current_value[30]),
    .C(current_value[29]),
    .D(current_value[28]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nor4_1 _288_ (
    .A(current_value[19]),
    .B(current_value[18]),
    .C(current_value[17]),
    .D(current_value[16]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor4_1 _289_ (
    .A(current_value[23]),
    .B(current_value[22]),
    .C(current_value[21]),
    .D(current_value[20]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand4_1 _290_ (
    .A(_101_),
    .B(_102_),
    .C(_103_),
    .D(_104_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__nor4_1 _291_ (
    .A(_098_),
    .B(_099_),
    .C(_100_),
    .D(_105_),
    .Y(done)
  );
  sky130_fd_sc_hd__and2_0 _292_ (
    .A(current_value[30]),
    .B(prev_value[30]),
    .X(_106_)
  );
  sky130_fd_sc_hd__xor2_1 _293_ (
    .A(current_value[29]),
    .B(prev_value[29]),
    .X(_107_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(current_value[28]),
    .B(prev_value[28]),
    .Y(_108_)
  );
  sky130_fd_sc_hd__xnor2_1 _295_ (
    .A(current_value[28]),
    .B(prev_value[28]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__and2_0 _296_ (
    .A(current_value[27]),
    .B(prev_value[27]),
    .X(_110_)
  );
  sky130_fd_sc_hd__nand2_1 _297_ (
    .A(current_value[27]),
    .B(prev_value[27]),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nor2_1 _298_ (
    .A(current_value[27]),
    .B(prev_value[27]),
    .Y(_112_)
  );
  sky130_fd_sc_hd__and2_0 _299_ (
    .A(current_value[26]),
    .B(prev_value[26]),
    .X(_113_)
  );
  sky130_fd_sc_hd__nor2_1 _300_ (
    .A(current_value[26]),
    .B(prev_value[26]),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2_1 _301_ (
    .A(_113_),
    .B(_114_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand2_1 _302_ (
    .A(current_value[25]),
    .B(prev_value[25]),
    .Y(_116_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _303_ (
    .A(current_value[25]),
    .SLEEP(prev_value[25]),
    .X(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _304_ (
    .A(current_value[24]),
    .B(prev_value[24]),
    .Y(_118_)
  );
  sky130_fd_sc_hd__xor2_1 _305_ (
    .A(current_value[24]),
    .B(prev_value[24]),
    .X(_119_)
  );
  sky130_fd_sc_hd__clkinv_1 _306_ (
    .A(_119_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__and2_0 _307_ (
    .A(current_value[23]),
    .B(prev_value[23]),
    .X(_121_)
  );
  sky130_fd_sc_hd__nor2_1 _308_ (
    .A(current_value[23]),
    .B(prev_value[23]),
    .Y(_122_)
  );
  sky130_fd_sc_hd__and2_0 _309_ (
    .A(current_value[22]),
    .B(prev_value[22]),
    .X(_123_)
  );
  sky130_fd_sc_hd__nor2_1 _310_ (
    .A(current_value[22]),
    .B(prev_value[22]),
    .Y(_124_)
  );
  sky130_fd_sc_hd__nor2_1 _311_ (
    .A(_123_),
    .B(_124_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nand2_1 _312_ (
    .A(current_value[21]),
    .B(prev_value[21]),
    .Y(_126_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _313_ (
    .A(current_value[21]),
    .SLEEP(prev_value[21]),
    .X(_127_)
  );
  sky130_fd_sc_hd__nand2_1 _314_ (
    .A(current_value[20]),
    .B(prev_value[20]),
    .Y(_128_)
  );
  sky130_fd_sc_hd__xnor2_1 _315_ (
    .A(current_value[20]),
    .B(prev_value[20]),
    .Y(_129_)
  );
  sky130_fd_sc_hd__nand2_1 _316_ (
    .A(current_value[19]),
    .B(prev_value[19]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__clkinv_1 _317_ (
    .A(_130_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _318_ (
    .A(current_value[19]),
    .B(prev_value[19]),
    .Y(_132_)
  );
  sky130_fd_sc_hd__and2_0 _319_ (
    .A(current_value[18]),
    .B(prev_value[18]),
    .X(_133_)
  );
  sky130_fd_sc_hd__nor2_1 _320_ (
    .A(current_value[18]),
    .B(prev_value[18]),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nor2_1 _321_ (
    .A(_133_),
    .B(_134_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand2_1 _322_ (
    .A(current_value[17]),
    .B(prev_value[17]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _323_ (
    .A(current_value[17]),
    .SLEEP(prev_value[17]),
    .X(_137_)
  );
  sky130_fd_sc_hd__nand2_1 _324_ (
    .A(current_value[16]),
    .B(prev_value[16]),
    .Y(_138_)
  );
  sky130_fd_sc_hd__xor2_1 _325_ (
    .A(current_value[16]),
    .B(prev_value[16]),
    .X(_139_)
  );
  sky130_fd_sc_hd__clkinv_1 _326_ (
    .A(_139_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand2_1 _327_ (
    .A(current_value[15]),
    .B(prev_value[15]),
    .Y(_141_)
  );
  sky130_fd_sc_hd__clkinv_1 _328_ (
    .A(_141_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _329_ (
    .A(current_value[15]),
    .B(prev_value[15]),
    .Y(_143_)
  );
  sky130_fd_sc_hd__and2_0 _330_ (
    .A(current_value[14]),
    .B(prev_value[14]),
    .X(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(current_value[14]),
    .B(prev_value[14]),
    .Y(_145_)
  );
  sky130_fd_sc_hd__nor2_1 _332_ (
    .A(_144_),
    .B(_145_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(current_value[13]),
    .B(prev_value[13]),
    .Y(_147_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _334_ (
    .A(current_value[13]),
    .SLEEP(prev_value[13]),
    .X(_148_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(current_value[12]),
    .B(prev_value[12]),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nor2_1 _336_ (
    .A(current_value[12]),
    .B(prev_value[12]),
    .Y(_150_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _337_ (
    .A(_149_),
    .SLEEP(_150_),
    .X(_151_)
  );
  sky130_fd_sc_hd__nand2_1 _338_ (
    .A(current_value[11]),
    .B(prev_value[11]),
    .Y(_152_)
  );
  sky130_fd_sc_hd__clkinv_1 _339_ (
    .A(_152_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nor2_1 _340_ (
    .A(current_value[11]),
    .B(prev_value[11]),
    .Y(_154_)
  );
  sky130_fd_sc_hd__and2_0 _341_ (
    .A(current_value[10]),
    .B(prev_value[10]),
    .X(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _342_ (
    .A(current_value[10]),
    .B(prev_value[10]),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2_1 _343_ (
    .A(_155_),
    .B(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__nand2_1 _344_ (
    .A(current_value[9]),
    .B(prev_value[9]),
    .Y(_158_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _345_ (
    .A(current_value[9]),
    .SLEEP(prev_value[9]),
    .X(_159_)
  );
  sky130_fd_sc_hd__nand2_1 _346_ (
    .A(current_value[8]),
    .B(prev_value[8]),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nor2_1 _347_ (
    .A(current_value[8]),
    .B(prev_value[8]),
    .Y(_161_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _348_ (
    .A(_160_),
    .SLEEP(_161_),
    .X(_162_)
  );
  sky130_fd_sc_hd__nand2_1 _349_ (
    .A(current_value[7]),
    .B(prev_value[7]),
    .Y(_163_)
  );
  sky130_fd_sc_hd__clkinv_1 _350_ (
    .A(_163_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nor2_1 _351_ (
    .A(current_value[7]),
    .B(prev_value[7]),
    .Y(_165_)
  );
  sky130_fd_sc_hd__and2_0 _352_ (
    .A(current_value[6]),
    .B(prev_value[6]),
    .X(_166_)
  );
  sky130_fd_sc_hd__nor2_1 _353_ (
    .A(current_value[6]),
    .B(prev_value[6]),
    .Y(_167_)
  );
  sky130_fd_sc_hd__nor2_1 _354_ (
    .A(_166_),
    .B(_167_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nand2_1 _355_ (
    .A(current_value[5]),
    .B(prev_value[5]),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nor2_1 _356_ (
    .A(current_value[5]),
    .B(prev_value[5]),
    .Y(_170_)
  );
  sky130_fd_sc_hd__clkinv_1 _357_ (
    .A(_170_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__nand2_1 _358_ (
    .A(current_value[4]),
    .B(prev_value[4]),
    .Y(_172_)
  );
  sky130_fd_sc_hd__xor2_1 _359_ (
    .A(current_value[4]),
    .B(prev_value[4]),
    .X(_173_)
  );
  sky130_fd_sc_hd__clkinv_1 _360_ (
    .A(_173_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nand2_1 _361_ (
    .A(current_value[3]),
    .B(prev_value[3]),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor2_1 _362_ (
    .A(current_value[3]),
    .B(prev_value[3]),
    .Y(_176_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _363_ (
    .A(current_value[3]),
    .SLEEP(prev_value[3]),
    .X(_177_)
  );
  sky130_fd_sc_hd__and2_0 _364_ (
    .A(current_value[2]),
    .B(prev_value[2]),
    .X(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _365_ (
    .A(current_value[1]),
    .B(prev_value[1]),
    .Y(_179_)
  );
  sky130_fd_sc_hd__nand2_1 _366_ (
    .A(current_value[0]),
    .B(prev_value[0]),
    .Y(_180_)
  );
  sky130_fd_sc_hd__nor2_1 _367_ (
    .A(current_value[1]),
    .B(prev_value[1]),
    .Y(_181_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _368_ (
    .A(_179_),
    .SLEEP(_181_),
    .X(_182_)
  );
  sky130_fd_sc_hd__o21ai_0 _369_ (
    .A1(_180_),
    .A2(_181_),
    .B1(_179_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__nor2_1 _370_ (
    .A(current_value[2]),
    .B(prev_value[2]),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nor2_1 _371_ (
    .A(_178_),
    .B(_184_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__a21o_1 _372_ (
    .A1(_183_),
    .A2(_185_),
    .B1(_178_),
    .X(_186_)
  );
  sky130_fd_sc_hd__a221oi_1 _373_ (
    .A1(current_value[3]),
    .A2(prev_value[3]),
    .B1(_183_),
    .B2(_185_),
    .C1(_178_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nor2_1 _374_ (
    .A(_176_),
    .B(_187_),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nor3_1 _375_ (
    .A(_174_),
    .B(_176_),
    .C(_187_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__a21oi_1 _376_ (
    .A1(current_value[4]),
    .A2(prev_value[4]),
    .B1(_189_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__o311ai_0 _377_ (
    .A1(_174_),
    .A2(_176_),
    .A3(_187_),
    .B1(_172_),
    .C1(_169_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__a21oi_1 _378_ (
    .A1(_169_),
    .A2(_190_),
    .B1(_170_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__a21o_1 _379_ (
    .A1(_168_),
    .A2(_192_),
    .B1(_166_),
    .X(_193_)
  );
  sky130_fd_sc_hd__a311oi_1 _380_ (
    .A1(_168_),
    .A2(_171_),
    .A3(_191_),
    .B1(_166_),
    .C1(_164_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__nor2_1 _381_ (
    .A(_165_),
    .B(_194_),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nand2_1 _382_ (
    .A(_162_),
    .B(_195_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nand2_1 _383_ (
    .A(_160_),
    .B(_196_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__o311ai_0 _384_ (
    .A1(_161_),
    .A2(_165_),
    .A3(_194_),
    .B1(_160_),
    .C1(_158_),
    .Y(_198_)
  );
  sky130_fd_sc_hd__and2_0 _385_ (
    .A(_159_),
    .B(_198_),
    .X(_199_)
  );
  sky130_fd_sc_hd__a21oi_1 _386_ (
    .A1(_157_),
    .A2(_199_),
    .B1(_155_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__a311oi_1 _387_ (
    .A1(_157_),
    .A2(_159_),
    .A3(_198_),
    .B1(_155_),
    .C1(_153_),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nor2_1 _388_ (
    .A(_154_),
    .B(_201_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nand2_1 _389_ (
    .A(_151_),
    .B(_202_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _390_ (
    .A(_149_),
    .B(_203_),
    .Y(_204_)
  );
  sky130_fd_sc_hd__o311ai_0 _391_ (
    .A1(_150_),
    .A2(_154_),
    .A3(_201_),
    .B1(_149_),
    .C1(_147_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__and2_0 _392_ (
    .A(_148_),
    .B(_205_),
    .X(_206_)
  );
  sky130_fd_sc_hd__a21oi_1 _393_ (
    .A1(_146_),
    .A2(_206_),
    .B1(_144_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__a311oi_1 _394_ (
    .A1(_146_),
    .A2(_148_),
    .A3(_205_),
    .B1(_144_),
    .C1(_142_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__nor2_1 _395_ (
    .A(_143_),
    .B(_208_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand2_1 _396_ (
    .A(_139_),
    .B(_209_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__o311ai_0 _397_ (
    .A1(_140_),
    .A2(_143_),
    .A3(_208_),
    .B1(_138_),
    .C1(_136_),
    .Y(_211_)
  );
  sky130_fd_sc_hd__and2_0 _398_ (
    .A(_137_),
    .B(_211_),
    .X(_212_)
  );
  sky130_fd_sc_hd__a21oi_1 _399_ (
    .A1(_135_),
    .A2(_212_),
    .B1(_133_),
    .Y(_213_)
  );
  sky130_fd_sc_hd__a311oi_1 _400_ (
    .A1(_135_),
    .A2(_137_),
    .A3(_211_),
    .B1(_133_),
    .C1(_131_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nor3_1 _401_ (
    .A(_129_),
    .B(_132_),
    .C(_214_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__o31ai_1 _402_ (
    .A1(_129_),
    .A2(_132_),
    .A3(_214_),
    .B1(_128_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__o311ai_0 _403_ (
    .A1(_129_),
    .A2(_132_),
    .A3(_214_),
    .B1(_128_),
    .C1(_126_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__and3_1 _404_ (
    .A(_125_),
    .B(_127_),
    .C(_217_),
    .X(_218_)
  );
  sky130_fd_sc_hd__nor2_1 _405_ (
    .A(_123_),
    .B(_218_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__a311oi_1 _406_ (
    .A1(_125_),
    .A2(_127_),
    .A3(_217_),
    .B1(_123_),
    .C1(_121_),
    .Y(_220_)
  );
  sky130_fd_sc_hd__nor2_1 _407_ (
    .A(_122_),
    .B(_220_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nand2_1 _408_ (
    .A(_119_),
    .B(_221_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__nand2_1 _409_ (
    .A(_118_),
    .B(_222_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__o311ai_0 _410_ (
    .A1(_120_),
    .A2(_122_),
    .A3(_220_),
    .B1(_118_),
    .C1(_116_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nand3_1 _411_ (
    .A(_115_),
    .B(_117_),
    .C(_224_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__a31oi_1 _412_ (
    .A1(_115_),
    .A2(_117_),
    .A3(_224_),
    .B1(_113_),
    .Y(_226_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _413_ (
    .A(_112_),
    .SLEEP(_226_),
    .X(_227_)
  );
  sky130_fd_sc_hd__a311oi_1 _414_ (
    .A1(_115_),
    .A2(_117_),
    .A3(_224_),
    .B1(_113_),
    .C1(_110_),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nor3_1 _415_ (
    .A(_109_),
    .B(_112_),
    .C(_228_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__o31ai_1 _416_ (
    .A1(_109_),
    .A2(_112_),
    .A3(_228_),
    .B1(_108_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__maj3_1 _417_ (
    .A(current_value[29]),
    .B(prev_value[29]),
    .C(_230_),
    .X(_231_)
  );
  sky130_fd_sc_hd__xnor2_1 _418_ (
    .A(current_value[30]),
    .B(prev_value[30]),
    .Y(_232_)
  );
  sky130_fd_sc_hd__clkinv_1 _419_ (
    .A(_232_),
    .Y(_233_)
  );
  sky130_fd_sc_hd__a21o_1 _420_ (
    .A1(_231_),
    .A2(_233_),
    .B1(_106_),
    .X(_234_)
  );
  sky130_fd_sc_hd__xor2_1 _421_ (
    .A(current_value[31]),
    .B(prev_value[31]),
    .X(_235_)
  );
  sky130_fd_sc_hd__a211oi_1 _422_ (
    .A1(_231_),
    .A2(_233_),
    .B1(_235_),
    .C1(_106_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__a211oi_1 _423_ (
    .A1(_234_),
    .A2(_235_),
    .B1(_236_),
    .C1(done),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nor2_1 _424_ (
    .A(_231_),
    .B(_233_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__a211oi_1 _425_ (
    .A1(_231_),
    .A2(_233_),
    .B1(_237_),
    .C1(done),
    .Y(_094_)
  );
  sky130_fd_sc_hd__a21oi_1 _426_ (
    .A1(_107_),
    .A2(_230_),
    .B1(done),
    .Y(_238_)
  );
  sky130_fd_sc_hd__o21a_1 _427_ (
    .A1(_107_),
    .A2(_230_),
    .B1(_238_),
    .X(_093_)
  );
  sky130_fd_sc_hd__a311oi_1 _428_ (
    .A1(_109_),
    .A2(_111_),
    .A3(_227_),
    .B1(_229_),
    .C1(done),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nor2_1 _429_ (
    .A(_110_),
    .B(_112_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__xor2_1 _430_ (
    .A(_226_),
    .B(_239_),
    .X(_240_)
  );
  sky130_fd_sc_hd__nor2_1 _431_ (
    .A(done),
    .B(_240_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__a21o_1 _432_ (
    .A1(_117_),
    .A2(_224_),
    .B1(_115_),
    .X(_241_)
  );
  sky130_fd_sc_hd__and3b_1 _433_ (
    .A_N(done),
    .B(_225_),
    .C(_241_),
    .X(_090_)
  );
  sky130_fd_sc_hd__nand2_1 _434_ (
    .A(_116_),
    .B(_117_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__xor2_1 _435_ (
    .A(_223_),
    .B(_242_),
    .X(_243_)
  );
  sky130_fd_sc_hd__nor2_1 _436_ (
    .A(done),
    .B(_243_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__nor2_1 _437_ (
    .A(_119_),
    .B(_221_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__a211oi_1 _438_ (
    .A1(_119_),
    .A2(_221_),
    .B1(_244_),
    .C1(done),
    .Y(_088_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _439_ (
    .A(_121_),
    .SLEEP(_122_),
    .X(_245_)
  );
  sky130_fd_sc_hd__xnor2_1 _440_ (
    .A(_219_),
    .B(_245_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__nor2_1 _441_ (
    .A(done),
    .B(_246_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__a21o_1 _442_ (
    .A1(_127_),
    .A2(_217_),
    .B1(_125_),
    .X(_247_)
  );
  sky130_fd_sc_hd__nor3b_1 _443_ (
    .A(done),
    .B(_218_),
    .C_N(_247_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__and2_0 _444_ (
    .A(_126_),
    .B(_127_),
    .X(_248_)
  );
  sky130_fd_sc_hd__xnor2_1 _445_ (
    .A(_216_),
    .B(_248_),
    .Y(_249_)
  );
  sky130_fd_sc_hd__nor2_1 _446_ (
    .A(done),
    .B(_249_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__o21ai_0 _447_ (
    .A1(_132_),
    .A2(_214_),
    .B1(_129_),
    .Y(_250_)
  );
  sky130_fd_sc_hd__nor3b_1 _448_ (
    .A(done),
    .B(_215_),
    .C_N(_250_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _449_ (
    .A(_131_),
    .B(_132_),
    .Y(_251_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _450_ (
    .A(_213_),
    .SLEEP(_251_),
    .X(_252_)
  );
  sky130_fd_sc_hd__nand2_1 _451_ (
    .A(_213_),
    .B(_251_),
    .Y(_253_)
  );
  sky130_fd_sc_hd__a21oi_1 _452_ (
    .A1(_252_),
    .A2(_253_),
    .B1(done),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nor2_1 _453_ (
    .A(_135_),
    .B(_212_),
    .Y(_254_)
  );
  sky130_fd_sc_hd__a211oi_1 _454_ (
    .A1(_135_),
    .A2(_212_),
    .B1(_254_),
    .C1(done),
    .Y(_082_)
  );
  sky130_fd_sc_hd__a22o_1 _455_ (
    .A1(_136_),
    .A2(_137_),
    .B1(_138_),
    .B2(_210_),
    .X(_255_)
  );
  sky130_fd_sc_hd__nand4_1 _456_ (
    .A(_136_),
    .B(_137_),
    .C(_138_),
    .D(_210_),
    .Y(_256_)
  );
  sky130_fd_sc_hd__a21oi_1 _457_ (
    .A1(_255_),
    .A2(_256_),
    .B1(done),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor2_1 _458_ (
    .A(_139_),
    .B(_209_),
    .Y(_257_)
  );
  sky130_fd_sc_hd__a211oi_1 _459_ (
    .A1(_139_),
    .A2(_209_),
    .B1(_257_),
    .C1(done),
    .Y(_080_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _460_ (
    .A(_142_),
    .SLEEP(_143_),
    .X(_258_)
  );
  sky130_fd_sc_hd__xnor2_1 _461_ (
    .A(_207_),
    .B(_258_),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nor2_1 _462_ (
    .A(done),
    .B(_259_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _463_ (
    .A(_146_),
    .B(_206_),
    .Y(_260_)
  );
  sky130_fd_sc_hd__a211oi_1 _464_ (
    .A1(_146_),
    .A2(_206_),
    .B1(_260_),
    .C1(done),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _465_ (
    .A(_147_),
    .B(_148_),
    .Y(_261_)
  );
  sky130_fd_sc_hd__xor2_1 _466_ (
    .A(_204_),
    .B(_261_),
    .X(_262_)
  );
  sky130_fd_sc_hd__nor2_1 _467_ (
    .A(done),
    .B(_262_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nor2_1 _468_ (
    .A(_151_),
    .B(_202_),
    .Y(_263_)
  );
  sky130_fd_sc_hd__a211oi_1 _469_ (
    .A1(_151_),
    .A2(_202_),
    .B1(_263_),
    .C1(done),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _470_ (
    .A(_153_),
    .B(_154_),
    .Y(_264_)
  );
  sky130_fd_sc_hd__xor2_1 _471_ (
    .A(_200_),
    .B(_264_),
    .X(_265_)
  );
  sky130_fd_sc_hd__nor2_1 _472_ (
    .A(done),
    .B(_265_),
    .Y(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _473_ (
    .A(_157_),
    .B(_199_),
    .Y(_266_)
  );
  sky130_fd_sc_hd__a211oi_1 _474_ (
    .A1(_157_),
    .A2(_199_),
    .B1(_266_),
    .C1(done),
    .Y(_074_)
  );
  sky130_fd_sc_hd__and2_0 _475_ (
    .A(_158_),
    .B(_159_),
    .X(_267_)
  );
  sky130_fd_sc_hd__xnor2_1 _476_ (
    .A(_197_),
    .B(_267_),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nor2_1 _477_ (
    .A(done),
    .B(_268_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _478_ (
    .A(_162_),
    .B(_195_),
    .Y(_269_)
  );
  sky130_fd_sc_hd__a211oi_1 _479_ (
    .A1(_162_),
    .A2(_195_),
    .B1(_269_),
    .C1(done),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor2_1 _480_ (
    .A(_164_),
    .B(_165_),
    .Y(_270_)
  );
  sky130_fd_sc_hd__xnor2_1 _481_ (
    .A(_193_),
    .B(_270_),
    .Y(_271_)
  );
  sky130_fd_sc_hd__nor2_1 _482_ (
    .A(done),
    .B(_271_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _483_ (
    .A(_168_),
    .B(_192_),
    .Y(_272_)
  );
  sky130_fd_sc_hd__a211oi_1 _484_ (
    .A1(_168_),
    .A2(_192_),
    .B1(_272_),
    .C1(done),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand2_1 _485_ (
    .A(_169_),
    .B(_171_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__xnor2_1 _486_ (
    .A(_190_),
    .B(_273_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__nor2_1 _487_ (
    .A(done),
    .B(_274_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _488_ (
    .A(_173_),
    .B(_188_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__nor3_1 _489_ (
    .A(done),
    .B(_189_),
    .C(_275_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__a21oi_1 _490_ (
    .A1(_175_),
    .A2(_177_),
    .B1(_186_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__a311oi_1 _491_ (
    .A1(_175_),
    .A2(_177_),
    .A3(_186_),
    .B1(_276_),
    .C1(done),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _492_ (
    .A(_183_),
    .B(_185_),
    .Y(_277_)
  );
  sky130_fd_sc_hd__a211oi_1 _493_ (
    .A1(_183_),
    .A2(_185_),
    .B1(_277_),
    .C1(done),
    .Y(_066_)
  );
  sky130_fd_sc_hd__xnor2_1 _494_ (
    .A(_180_),
    .B(_182_),
    .Y(_278_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _495_ (
    .A(done),
    .SLEEP(_278_),
    .X(_065_)
  );
  sky130_fd_sc_hd__xnor2_1 _496_ (
    .A(current_value[0]),
    .B(prev_value[0]),
    .Y(_279_)
  );
  sky130_fd_sc_hd__nor2_1 _497_ (
    .A(done),
    .B(_279_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__clkinv_1 _498_ (
    .A(rst),
    .Y(_061_)
  );
  sky130_fd_sc_hd__clkinv_1 _499_ (
    .A(rst),
    .Y(_060_)
  );
  sky130_fd_sc_hd__clkinv_1 _500_ (
    .A(rst),
    .Y(_059_)
  );
  sky130_fd_sc_hd__clkinv_1 _501_ (
    .A(rst),
    .Y(_058_)
  );
  sky130_fd_sc_hd__clkinv_1 _502_ (
    .A(rst),
    .Y(_057_)
  );
  sky130_fd_sc_hd__clkinv_1 _503_ (
    .A(rst),
    .Y(_056_)
  );
  sky130_fd_sc_hd__clkinv_1 _504_ (
    .A(rst),
    .Y(_055_)
  );
  sky130_fd_sc_hd__clkinv_1 _505_ (
    .A(rst),
    .Y(_054_)
  );
  sky130_fd_sc_hd__clkinv_1 _506_ (
    .A(rst),
    .Y(_053_)
  );
  sky130_fd_sc_hd__clkinv_1 _507_ (
    .A(rst),
    .Y(_052_)
  );
  sky130_fd_sc_hd__clkinv_1 _508_ (
    .A(rst),
    .Y(_051_)
  );
  sky130_fd_sc_hd__clkinv_1 _509_ (
    .A(rst),
    .Y(_050_)
  );
  sky130_fd_sc_hd__clkinv_1 _510_ (
    .A(rst),
    .Y(_049_)
  );
  sky130_fd_sc_hd__clkinv_1 _511_ (
    .A(rst),
    .Y(_048_)
  );
  sky130_fd_sc_hd__clkinv_1 _512_ (
    .A(rst),
    .Y(_047_)
  );
  sky130_fd_sc_hd__clkinv_1 _513_ (
    .A(rst),
    .Y(_046_)
  );
  sky130_fd_sc_hd__clkinv_1 _514_ (
    .A(rst),
    .Y(_045_)
  );
  sky130_fd_sc_hd__clkinv_1 _515_ (
    .A(rst),
    .Y(_044_)
  );
  sky130_fd_sc_hd__clkinv_1 _516_ (
    .A(rst),
    .Y(_043_)
  );
  sky130_fd_sc_hd__clkinv_1 _517_ (
    .A(rst),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _518_ (
    .A(rst),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _519_ (
    .A(rst),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _520_ (
    .A(rst),
    .Y(_039_)
  );
  sky130_fd_sc_hd__clkinv_1 _521_ (
    .A(rst),
    .Y(_038_)
  );
  sky130_fd_sc_hd__clkinv_1 _522_ (
    .A(rst),
    .Y(_037_)
  );
  sky130_fd_sc_hd__clkinv_1 _523_ (
    .A(rst),
    .Y(_036_)
  );
  sky130_fd_sc_hd__clkinv_1 _524_ (
    .A(rst),
    .Y(_035_)
  );
  sky130_fd_sc_hd__clkinv_1 _525_ (
    .A(rst),
    .Y(_034_)
  );
  sky130_fd_sc_hd__clkinv_1 _526_ (
    .A(rst),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _527_ (
    .A(rst),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _528_ (
    .A(rst),
    .Y(_031_)
  );
  sky130_fd_sc_hd__clkinv_1 _529_ (
    .A(rst),
    .Y(_030_)
  );
  sky130_fd_sc_hd__clkinv_1 _530_ (
    .A(rst),
    .Y(_029_)
  );
  sky130_fd_sc_hd__clkinv_1 _531_ (
    .A(rst),
    .Y(_028_)
  );
  sky130_fd_sc_hd__clkinv_1 _532_ (
    .A(rst),
    .Y(_027_)
  );
  sky130_fd_sc_hd__clkinv_1 _533_ (
    .A(rst),
    .Y(_026_)
  );
  sky130_fd_sc_hd__clkinv_1 _534_ (
    .A(rst),
    .Y(_025_)
  );
  sky130_fd_sc_hd__clkinv_1 _535_ (
    .A(rst),
    .Y(_024_)
  );
  sky130_fd_sc_hd__clkinv_1 _536_ (
    .A(rst),
    .Y(_023_)
  );
  sky130_fd_sc_hd__clkinv_1 _537_ (
    .A(rst),
    .Y(_022_)
  );
  sky130_fd_sc_hd__clkinv_1 _538_ (
    .A(rst),
    .Y(_021_)
  );
  sky130_fd_sc_hd__clkinv_1 _539_ (
    .A(rst),
    .Y(_020_)
  );
  sky130_fd_sc_hd__clkinv_1 _540_ (
    .A(rst),
    .Y(_019_)
  );
  sky130_fd_sc_hd__clkinv_1 _541_ (
    .A(rst),
    .Y(_018_)
  );
  sky130_fd_sc_hd__clkinv_1 _542_ (
    .A(rst),
    .Y(_017_)
  );
  sky130_fd_sc_hd__clkinv_1 _543_ (
    .A(rst),
    .Y(_016_)
  );
  sky130_fd_sc_hd__clkinv_1 _544_ (
    .A(rst),
    .Y(_015_)
  );
  sky130_fd_sc_hd__clkinv_1 _545_ (
    .A(rst),
    .Y(_014_)
  );
  sky130_fd_sc_hd__clkinv_1 _546_ (
    .A(rst),
    .Y(_013_)
  );
  sky130_fd_sc_hd__clkinv_1 _547_ (
    .A(rst),
    .Y(_012_)
  );
  sky130_fd_sc_hd__clkinv_1 _548_ (
    .A(rst),
    .Y(_011_)
  );
  sky130_fd_sc_hd__clkinv_1 _549_ (
    .A(rst),
    .Y(_010_)
  );
  sky130_fd_sc_hd__clkinv_1 _550_ (
    .A(rst),
    .Y(_009_)
  );
  sky130_fd_sc_hd__clkinv_1 _551_ (
    .A(rst),
    .Y(_008_)
  );
  sky130_fd_sc_hd__clkinv_1 _552_ (
    .A(rst),
    .Y(_007_)
  );
  sky130_fd_sc_hd__clkinv_1 _553_ (
    .A(rst),
    .Y(_006_)
  );
  sky130_fd_sc_hd__clkinv_1 _554_ (
    .A(rst),
    .Y(_005_)
  );
  sky130_fd_sc_hd__clkinv_1 _555_ (
    .A(rst),
    .Y(_004_)
  );
  sky130_fd_sc_hd__clkinv_1 _556_ (
    .A(rst),
    .Y(_003_)
  );
  sky130_fd_sc_hd__clkinv_1 _557_ (
    .A(rst),
    .Y(_002_)
  );
  sky130_fd_sc_hd__clkinv_1 _558_ (
    .A(rst),
    .Y(_001_)
  );
  sky130_fd_sc_hd__clkinv_1 _559_ (
    .A(rst),
    .Y(_000_)
  );
  sky130_fd_sc_hd__nor4_1 _560_ (
    .A(_098_),
    .B(_099_),
    .C(_100_),
    .D(_105_),
    .Y(result[1])
  );
  sky130_fd_sc_hd__clkinv_1 _561_ (
    .A(rst),
    .Y(_063_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfstp_2 _562_ (
    .CLK(clk),
    .D(_064_),
    .Q(current_value[0]),
    .SET_B(_000_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _563_ (
    .CLK(clk),
    .D(_065_),
    .Q(current_value[1]),
    .RESET_B(_001_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _564_ (
    .CLK(clk),
    .D(_066_),
    .Q(current_value[2]),
    .RESET_B(_002_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _565_ (
    .CLK(clk),
    .D(_067_),
    .Q(current_value[3]),
    .RESET_B(_003_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _566_ (
    .CLK(clk),
    .D(_068_),
    .Q(current_value[4]),
    .RESET_B(_004_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _567_ (
    .CLK(clk),
    .D(_069_),
    .Q(current_value[5]),
    .RESET_B(_005_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _568_ (
    .CLK(clk),
    .D(_070_),
    .Q(current_value[6]),
    .RESET_B(_006_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _569_ (
    .CLK(clk),
    .D(_071_),
    .Q(current_value[7]),
    .RESET_B(_007_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _570_ (
    .CLK(clk),
    .D(_072_),
    .Q(current_value[8]),
    .RESET_B(_008_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _571_ (
    .CLK(clk),
    .D(_073_),
    .Q(current_value[9]),
    .RESET_B(_009_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _572_ (
    .CLK(clk),
    .D(_074_),
    .Q(current_value[10]),
    .RESET_B(_010_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _573_ (
    .CLK(clk),
    .D(_075_),
    .Q(current_value[11]),
    .RESET_B(_011_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _574_ (
    .CLK(clk),
    .D(_076_),
    .Q(current_value[12]),
    .RESET_B(_012_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _575_ (
    .CLK(clk),
    .D(_077_),
    .Q(current_value[13]),
    .RESET_B(_013_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _576_ (
    .CLK(clk),
    .D(_078_),
    .Q(current_value[14]),
    .RESET_B(_014_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _577_ (
    .CLK(clk),
    .D(_079_),
    .Q(current_value[15]),
    .RESET_B(_015_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _578_ (
    .CLK(clk),
    .D(_080_),
    .Q(current_value[16]),
    .RESET_B(_016_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _579_ (
    .CLK(clk),
    .D(_081_),
    .Q(current_value[17]),
    .RESET_B(_017_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _580_ (
    .CLK(clk),
    .D(_082_),
    .Q(current_value[18]),
    .RESET_B(_018_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _581_ (
    .CLK(clk),
    .D(_083_),
    .Q(current_value[19]),
    .RESET_B(_019_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _582_ (
    .CLK(clk),
    .D(_084_),
    .Q(current_value[20]),
    .RESET_B(_020_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _583_ (
    .CLK(clk),
    .D(_085_),
    .Q(current_value[21]),
    .RESET_B(_021_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _584_ (
    .CLK(clk),
    .D(_086_),
    .Q(current_value[22]),
    .RESET_B(_022_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _585_ (
    .CLK(clk),
    .D(_087_),
    .Q(current_value[23]),
    .RESET_B(_023_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _586_ (
    .CLK(clk),
    .D(_088_),
    .Q(current_value[24]),
    .RESET_B(_024_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _587_ (
    .CLK(clk),
    .D(_089_),
    .Q(current_value[25]),
    .RESET_B(_025_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _588_ (
    .CLK(clk),
    .D(_090_),
    .Q(current_value[26]),
    .RESET_B(_026_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _589_ (
    .CLK(clk),
    .D(_091_),
    .Q(current_value[27]),
    .RESET_B(_027_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _590_ (
    .CLK(clk),
    .D(_092_),
    .Q(current_value[28]),
    .RESET_B(_028_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _591_ (
    .CLK(clk),
    .D(_093_),
    .Q(current_value[29]),
    .RESET_B(_029_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _592_ (
    .CLK(clk),
    .D(_094_),
    .Q(current_value[30]),
    .RESET_B(_030_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _593_ (
    .CLK(clk),
    .D(_095_),
    .Q(current_value[31]),
    .RESET_B(_031_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _594_ (
    .CLK(clk),
    .D(current_value[0]),
    .Q(prev_value[0]),
    .RESET_B(_032_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _595_ (
    .CLK(clk),
    .D(current_value[1]),
    .Q(prev_value[1]),
    .RESET_B(_033_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _596_ (
    .CLK(clk),
    .D(current_value[2]),
    .Q(prev_value[2]),
    .RESET_B(_034_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _597_ (
    .CLK(clk),
    .D(current_value[3]),
    .Q(prev_value[3]),
    .RESET_B(_035_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _598_ (
    .CLK(clk),
    .D(current_value[4]),
    .Q(prev_value[4]),
    .RESET_B(_036_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _599_ (
    .CLK(clk),
    .D(current_value[5]),
    .Q(prev_value[5]),
    .RESET_B(_037_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _600_ (
    .CLK(clk),
    .D(current_value[6]),
    .Q(prev_value[6]),
    .RESET_B(_038_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _601_ (
    .CLK(clk),
    .D(current_value[7]),
    .Q(prev_value[7]),
    .RESET_B(_039_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _602_ (
    .CLK(clk),
    .D(current_value[8]),
    .Q(prev_value[8]),
    .RESET_B(_040_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _603_ (
    .CLK(clk),
    .D(current_value[9]),
    .Q(prev_value[9]),
    .RESET_B(_041_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _604_ (
    .CLK(clk),
    .D(current_value[10]),
    .Q(prev_value[10]),
    .RESET_B(_042_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _605_ (
    .CLK(clk),
    .D(current_value[11]),
    .Q(prev_value[11]),
    .RESET_B(_043_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _606_ (
    .CLK(clk),
    .D(current_value[12]),
    .Q(prev_value[12]),
    .RESET_B(_044_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _607_ (
    .CLK(clk),
    .D(current_value[13]),
    .Q(prev_value[13]),
    .RESET_B(_045_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _608_ (
    .CLK(clk),
    .D(current_value[14]),
    .Q(prev_value[14]),
    .RESET_B(_046_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _609_ (
    .CLK(clk),
    .D(current_value[15]),
    .Q(prev_value[15]),
    .RESET_B(_047_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _610_ (
    .CLK(clk),
    .D(current_value[16]),
    .Q(prev_value[16]),
    .RESET_B(_048_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _611_ (
    .CLK(clk),
    .D(current_value[17]),
    .Q(prev_value[17]),
    .RESET_B(_049_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _612_ (
    .CLK(clk),
    .D(current_value[18]),
    .Q(prev_value[18]),
    .RESET_B(_050_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _613_ (
    .CLK(clk),
    .D(current_value[19]),
    .Q(prev_value[19]),
    .RESET_B(_051_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _614_ (
    .CLK(clk),
    .D(current_value[20]),
    .Q(prev_value[20]),
    .RESET_B(_052_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _615_ (
    .CLK(clk),
    .D(current_value[21]),
    .Q(prev_value[21]),
    .RESET_B(_053_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _616_ (
    .CLK(clk),
    .D(current_value[22]),
    .Q(prev_value[22]),
    .RESET_B(_054_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _617_ (
    .CLK(clk),
    .D(current_value[23]),
    .Q(prev_value[23]),
    .RESET_B(_055_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _618_ (
    .CLK(clk),
    .D(current_value[24]),
    .Q(prev_value[24]),
    .RESET_B(_056_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _619_ (
    .CLK(clk),
    .D(current_value[25]),
    .Q(prev_value[25]),
    .RESET_B(_057_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _620_ (
    .CLK(clk),
    .D(current_value[26]),
    .Q(prev_value[26]),
    .RESET_B(_058_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _621_ (
    .CLK(clk),
    .D(current_value[27]),
    .Q(prev_value[27]),
    .RESET_B(_059_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _622_ (
    .CLK(clk),
    .D(current_value[28]),
    .Q(prev_value[28]),
    .RESET_B(_060_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _623_ (
    .CLK(clk),
    .D(current_value[29]),
    .Q(prev_value[29]),
    .RESET_B(_061_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _624_ (
    .CLK(clk),
    .D(current_value[30]),
    .Q(prev_value[30]),
    .RESET_B(_062_)
  );
  (* src = "fibonacci.sv:26.2-34.5" *)
  sky130_fd_sc_hd__dfrtp_1 _625_ (
    .CLK(clk),
    .D(current_value[31]),
    .Q(prev_value[31]),
    .RESET_B(_063_)
  );
  assign { result[31:2], result[0] } = 31'h00000000;
endmodule
